### ISSUE TITLE
[chore]: Implement semantic-release for automated framework releases

### ISSUE THREAD

**Issue by dregatos** [nedap/segnify-ios#65]
As part of nedap/healthcare-mobile-focus-group#22 epic.

Ensure that this repo implements the Github workflows to achieve fully automated SPM releases.

```[tasklist]
### Tasks
- [ ] Make main the default branch
- [ ] Remove branch protection for main branch (if needed)
- [ ] Disable "allow merge commits"
- [ ] Enable "allow squash merges"
- [ ] Rename any existing tags to match version tag convention defined here, update existing GitHub releases
- [ ] Adds GitHub workflow to test the title of PRs matches semantic-release conventions
- [ ] Adds GitHub workflow to release the framework for commits to main using semantic-release
- [ ] Delete develop branch
```
